
export const SET_BUDGET="SET_BUDGET";
export const ADD_EXPENSE="ADD_EXPENSE";
export const ADD_CITY="ADD_CITY"
export const DELETE_EXPENSE="DELETE_EXPENSE"
export const EDIT_EXPENSE="EDIT_EXPENSE";
export const RESET_FORM="RESET_FORM"